if-shell '[[ $(tmux -V | cut -d" " -f2 | tr -d "a-z") -ge 3.2 ]]' \
    "set-option -sa terminal-features 'xterm-256color:RGB'"

if-shell '[[ $(tmux -V | cut -d" " -f2 | tr -d "a-z") -lt 3.2 ]]' \
    "set-option -ga terminal-overrides 'xterm-256color:Tc'"

# fix terminal color depth
#set -g default-terminal "screen-256color"
set -g default-terminal "xterm-256color"

set-window-option -g automatic-rename on
set-option -g set-titles on

set -g pane-border-format "#{pane_index} #{pane_title}"
set -g pane-border-status bottom

bind -n  C-0 select-pane -t 0
bind -n  C-1 select-pane -t 1
bind -n  C-2 select-pane -t 2
bind -n  C-3 select-pane -t 3
bind -n  C-4 select-pane -t 4
bind -n  C-5 select-pane -t 5
bind -n  C-6 select-pane -t 6
bind -n  C-7 select-pane -t 7
bind -n  C-8 select-pane -t 8
bind -n  C-9 select-pane -t 9


# easy config refreshes
bind r source-file ${HOME}/.tmux.conf \; display-message "source-file reloaded"

bind q set-window-option synchronize-panes on; # display-message "sync on"
bind a set-window-option synchronize-panes off; # display-message "sync off"

# split panes using s and v (as in :vs and :sp)
bind - split-window -v
bind | split-window -h
unbind '"'
unbind %

# fix clipboard access in macOS
#set-option -g default-command "~/bin/safe-reattach-to-user-namespace.sh -l zsh"

# vim keys
setw -g mode-keys vi

set-option -sg escape-time 10
set-option -g focus-events on
